# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
